/**
 * Shared files — generated regardless of which adapters are selected.
 * These are the state files and core infrastructure that all adapters share.
 */

export function getSharedFiles({ fullAgents, llmMode }) {
  const files = {};

  // ─── State files ────────────────────────────────────────────────
  files['.agents/state.json'] = JSON.stringify({
    project: {
      name: '',
      description: '',
      status: 'not_started'
    },
    mode: 'manual',
    context: {
      blocked_on: null,
      current_task: null
    },
    tasks: [],
    handoff: {
      from: null,
      to: null,
      approved_by_user: false
    },
    changelog: [],
    last_updated: new Date().toISOString(),
    last_updated_by: 'scaffold'
  }, null, 2) + '\n';

  files['.agents/state.md'] = `# Project Dashboard

> Auto-generated by create-agent-boilerplate. Updated by agents each session.

## Status: Not Started

## Current Task
_None — run /init-project to begin._

## Recent Activity
- Scaffolded by create-agent-boilerplate

## Blockers
_None_
`;

  files['.agents/workspace-map.md'] = `# Workspace Map

> Updated by agents whenever files are created, moved, or deleted.
> Agents read this to orient themselves instead of scanning the entire codebase.

## Project Structure

_To be populated by /init-project._

## Key Directories
_To be populated when the project is scaffolded by the Manager._

## Key Files
_To be populated as the project grows._
`;

  files['.agents/handoff.md'] = `# Handoff

_No active handoff. Manager will write here when delegating work._
`;

  // ─── Gitignore (template version — commits agent files) ─────────
  files['.gitignore'] = `# Dependencies
node_modules/
vendor/
__pycache__/
*.pyc
.venv/
venv/

# Build outputs
dist/
build/
.next/
out/

# Environment & secrets
.env
.env.local
.env.*.local

# IDE
.vscode/settings.json
.idea/

# OS
.DS_Store
Thumbs.db
`;

  // ─── Gitignore (project version — strips agent files) ───────────
  files['.gitignore.project'] = `# Agent System Files
.agents/state.json
.agents/state.md
.agents/handoff.md
.agents/
.github/agents/
.github/prompts/
.github/skills/
.github/copilot-instructions.md
.cursor/
.clinerules/
.windsurfrules
.claude/
.gemini/
.boilerplate/
boilerplate.config.json
CLAUDE.md
AGENTS.md
GEMINI.md

# Dependencies
node_modules/
vendor/
__pycache__/
*.pyc
.venv/
venv/

# Build outputs
dist/
build/
.next/
out/

# Environment & secrets
.env
.env.local
.env.*.local

# IDE
.vscode/settings.json
.idea/

# OS
.DS_Store
Thumbs.db
`;

  // ─── README ─────────────────────────────────────────────────────
  const agentList = fullAgents
    ? 'Manager, Engineer, Security, Designer, Researcher, Consultant, Medic'
    : 'Manager, Engineer, Security';

  files['README.md'] = `# Project Name

> Scaffolded with [Attacca](https://github.com/adihebbalae/Attacca)

## Quick Start

1. Open this folder in your IDE
2. Select the **Manager** agent
3. Run \`/init-project\` with your PRD

## Agents

${agentList}

## Configuration

See \`boilerplate.config.json\` for scaffold settings.
LLM mode: **${llmMode}**
`;

  return files;
}
